Add the fails to the github actions

diff --git a/.github/workflows/youtube_base.yml b/.github/workflows/youtube_base.yml
--- a/.github/workflows/youtube_base.yml
+++ b/.github/workflows/youtube_base.yml
@@ -25,4 +25,10 @@ jobs:
       - name: Poetry install
         run: poetry install
       - name: Run pytest
-        run: poetry run pytest -v
+        run: |
+          poetry run pytest -v
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Aborting push."
+            exit 1
+          fi
+          
